/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8e5c6221-4ca9-4b48-be88-20c36a48823e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TsvMHMWrA",
    "aws_user_pools_web_client_id": "7j9sja81vhqhd371u3t1q9kga3",
    "oauth": {}
};


export default awsmobile;
